from .client import RelayAuthClient
from .errors import (
    IdentityNotFoundError,
    IdentitySuspendedError,
    InsufficientScopeError,
    InvalidScopeError,
    RelayAuthError,
    TokenExpiredError,
    TokenRevokedError,
)
from .scopes import ScopeChecker, match_scope, parse_scope, parse_scopes, validate_scope
from .types import (
    AgentIdentity,
    AuditEntry,
    AuditQuery,
    Claims,
    CreateIdentityInput,
    IdentityStatus,
    IdentityType,
    ParsedScope,
    Policy,
    PolicyCondition,
    RelayAuthTokenClaims,
    Role,
    ScopeTemplate,
    TokenBudget,
    TokenPair,
)
from .verifier import TokenVerifier, VerifyOptions

__all__ = [
    "AgentIdentity",
    "AuditEntry",
    "AuditQuery",
    "Claims",
    "CreateIdentityInput",
    "IdentityNotFoundError",
    "IdentityStatus",
    "IdentitySuspendedError",
    "IdentityType",
    "InsufficientScopeError",
    "InvalidScopeError",
    "ParsedScope",
    "Policy",
    "PolicyCondition",
    "RelayAuthClient",
    "RelayAuthError",
    "RelayAuthTokenClaims",
    "Role",
    "ScopeChecker",
    "ScopeTemplate",
    "TokenBudget",
    "TokenExpiredError",
    "TokenPair",
    "TokenRevokedError",
    "TokenVerifier",
    "VerifyOptions",
    "match_scope",
    "parse_scope",
    "parse_scopes",
    "validate_scope",
]
